### ISSUE TITLE
Install error 

### ISSUE THREAD

**Issue by dougg0k** [AndyFilter/YeetMouse#11]
By running `sudo pacman -U pkg/build/leetmouse*.zst`

I got 
```
...
==> dkms install --no-depmod leetmouse-driver/0.9.0 -k 6.11.7-2-cachyos

Error! Bad return status for module build on kernel: 6.11.7-2-cachyos (x86_64)
Consult /var/lib/dkms/leetmouse-driver/0.9.0/build/make.log for more information.
==> WARNING: `dkms install --no-depmod leetmouse-driver/0.9.0 -k 6.11.7-2-cachyos' exited 10
==> ERROR: Missing 6.11.6-arch1-1 kernel modules tree for module leetmouse-driver/0.9.0.
(4/5) Updating linux initcpios...
...
```

```
❯ cat /var/lib/dkms/leetmouse-driver/0.9.0/build/make.log

   1   │ DKMS make.log for leetmouse-driver-0.9.0 for kernel 6.11.7-2-cachyos (x86_64)
   2   │ ter 12 nov 2024 21:42:23 -03
   3   │
   4   │ :: Compiling leetmouse kernel module
   5   │ ========================================
   6   │ make -C /lib/modules/6.11.7-2-cachyos/build M=/var/lib/dkms/leetmouse-driver/0.9.0/build/driver modules
   7   │ make[1]: Entering directory '/usr/lib/modules/6.11.7-2-cachyos/build'
   8   │   CC [M]  /var/lib/dkms/leetmouse-driver/0.9.0/build/driver/accel.o
   9   │ clang: error: unknown argument: '-mpreferred-stack-boundary=4'
  10   │ make[3]: *** [scripts/Makefile.build:244: /var/lib/dkms/leetmouse-driver/0.9.0/build/driver/accel.o] Error 1
  11   │ make[2]: *** [/usr/lib/modules/6.11.7-2-cachyos/build/Makefile:1934: /var/lib/dkms/leetmouse-driver/0.9.0/build/driver] Error 2
  12   │ make[1]: *** [Makefile:224: __sub-make] Error 2
  13   │ make[1]: Leaving directory '/usr/lib/modules/6.11.7-2-cachyos/build'
  14   │ make: *** [Makefile:37: driver] Error 2
```

And It didnt work.

```
❯ sudo -E ./gui/YeetMouseGui
LeetMouse directory doesnt exist!
Install the driver first, or check the parameters path.
```

**Comment by AndyFilter** [comment]
Hey, thanks for reporting the issue. It looks like `-mpreferred-stack-boundary` gcc flag is causing some issues. Which is fair as it might be OS specific. I'll be fair with you, I'm not completely sure what was the point of that flag in the original repository. I've run some tests without this flag and the program (unsurprisingly) seems to work just fine, so I'll just remove the flag; it defaults to 4 either way, so removing it shouldn't change anything on systems that support it.

**Comment by dougg0k** [comment]
That error is gone, but there still one, not sure if it's expecting the oficial kernel rather than being flexible.

`==> ERROR: Missing 6.11.6-arch1-1 kernel modules tree for module leetmouse-driver/0.9.0.`

**Comment by dougg0k** [comment]
Now the GUI works, but after pressing on the `Devices` tab. It crashes without any error.

```
nu ✗ sudo -E ./gui/YeetMouseGui
Error: nu::shell::terminated_by_signal

  × External command was terminated by a signal
   ╭─[entry #3:1:1]
 1 │ sudo -E ./gui/YeetMouseGui
   · ──┬─
   ·   ╰── terminated by SIGSEGV (11)
   ╰────
```

**Comment by AndyFilter** [comment]
When it comes to `ERROR: Missing 6.11.6-arch1-1 kernel modules tree` I don't think I can really help more. I personally don't use *arch*, and I'm not too knowledgeful about Linux as a whole, only think I can recommend is to download the latest build-essentials, and hope it somehow works.

As for other things.
1. Devices Tab
This is a bit complicated, as I can only test the code on Ubuntu 24.04. But that might not even be the issue, because I simply can't reproduce some issues that are caused by specific hardware being plugged into the computer. Either way, I'll try to make that code more bullet proof in the future. As for now tho, there's nothing you'd be interested in if the program works as it should, and detects all your input devices. But I will put a warning of some kind of that tab to only enter it if there are issues with the program, as it's useless in any other case.
2. Yes, tooltips would be very useful. Some (more important) tooltips are already in place, but the rest are coming in the future with the proper naming patch (#6).
3. Anisotropy is also planed for the future, recently someone asked for it on Reddit. But I personally don't see it as the top most priority, because I feel like it's something not many people use.
4. `Pre-Scale`, yes, the information "800/DPI" means that the value should be set to 800/(Your DPI). So for example if your DPI is 400 then you should set the Pre-Scale value to 800/400 = 2. It's there to make the program adjust to your DPI, not to force you to use 800DPI. I guess I didn't make it clear enough. I think changing the tooltip from `Used to adjust for DPI (...)` to `Used to adjust for different DPI settings (...)` would help.
As for the Graph, it visualizes the acceleration curve of your mouse. What you see is what you get (after applying, obviously). The `Mouse Smoothness` parameter was intentionally placed away from the configuration parameters, as it doesn't affect either the visual graph, or the mouse acceleration, all it does it smooth out your mouse input for the little green dot called `Mouse Speed` showing it's current speed. I understand the confusion tho, and I would like to change it's name, if you have any suggestions, feel free to share them with me.
5. Motivity support is coming to RawAccel, yes. Though it's currently not planned for Yeetmouse. There is something I want to add that would allow anyone to create fully customizable curves, but it's probably (unfortunately) a far future.
6. `Settings values directly`. Yes, I know I have to add tooltips (#10)
7. `I apply values, but I dont sense any difference in mouse movement` Did you get the driver to work? You had some errors installing it from what I understand. I can't help without more details about this. Try reinstalling the driver :)

As You can see, there's quite a bit planned for the future, unfortunately time is very scarce for me right now.

**Comment by dougg0k** [comment]
Ok, cool.

**Comment by dougg0k** [comment]
Just to add, another weird behavior.

After setting a accel profile, if I close the app and come back, it's as if it was reset, it doesnt go back to where it is set. Plus the settings are reset also there. So unsure, if the settings are still active and it's only the app, or not.

**Comment by AndyFilter** [comment]
This is obviously not the expected behavior, the parameters are saved in the `/sys/module/leetmouse/parameters` directory. If they are not, then either the driver was not properly installed, or the program is not run with `sudo` privileges. In both cases you should see alerts (red text) on the program telling you what's wrong. Also, the changes are applied **only** after clicking the **Apply** button, but that should go without saying.
Please make sure the driver is installed (for example by: `lsmod | grep leetmouse`), and that you're running the `YeetMouse` gui as advised in the `ReadMe` which is `sudo -E ./YeetMouseGui`.
If this doesn't help, the issue might be with the OS You're using, and at that point I unfortunately can no longer help You.

**Comment by dougg0k** [comment]
I see the params there, the values seem to be there.

```
❯ lsmod | grep leetmouse
leetmouse              45056  0
```

Yes, I do run with sudo, otherwise the tool does not open.

**Comment by dougg0k** [comment]
Yep, just found out, it's not when I close the tool, but when I restart the OS.

Before the value I set was `3.43`, now after a reboot.

```
nu ❯ ^cat /sys/module/leetmouse/parameters/Acceleration
644245120ll
```

**Comment by kitten** [comment]
@dougg0k Values aren't preserved. The only way to preserve them is basically to have a udev script that applies them. Of course it could apply them from a save file, but it comes down to that kind of approach

**Comment by dougg0k** [comment]
It's already not good as you have to use the slider to set values, if I find a good combination and lose afterwards, makes the tool not very nice to use.

**Comment by AndyFilter** [comment]
I'm a bit lost as to what's happening, and why You are experiencing this issue. But I've been planning on adding Import/Export for some time now as stated here: https://github.com/AndyFilter/YeetMouse/blob/793b86ce6b0a1afd1fafcfeb9c79c7b30f4594a4/gui/main.cpp#L11-L13
So that should help you just a bit I suppose.

But it's not really a solution, I would like to know more about this issue (we could open another issue, if more people are experiencing this). Like for example, when you restart your computer, do you not get the values you've put last time in the GUI? I mean like, all the values in the GUI are back to the default? 

Also, about the `cat /sys/module/leetmouse/parameters/Acceleration` output You sent. That's just the `long long` representation of the underlying fixed-point number. You should never (have to) edit these parameters by hand, they are there just in case You do something bad and You can't use GUI.

**Comment by dougg0k** [comment]
Like I said above, before the restart, it was a value that I had set through the GUI, after restart, it was another.

**Comment by AndyFilter** [comment]
I mean, the issue sounds pretty serious. If I understand correctly, You have to set the driver parameters **every time** you boot the system. Is that correct? (btw. I'm assuming everything is done through GUI, and the `/sys/module/leetmouse/parameters` files are never touched)

**Comment by dougg0k** [comment]
Exactly. Every boot through the GUI.

**Comment by AndyFilter** [comment]
That's bad, but I think I understand the issue. The driver _loads_ the parameters from `config_sample.h` (or later `config.h`) during build, and then it sets these values as the default after boot. This took me so long to understand, because I have my settings that I've been using for years in the `config.h`, so it's always set exactly how I want it to be.

Now, that I now what's going on, I'll try to prioritize the *Import/Export* function, and later some way to maybe load the acceleration parameters on boot. But from what I've read the second part might be a bit complicated.

For now, I recommend you to find settings you're comfortable with using the GUI and then putting those values into the `config.h` files. **BUT FIRST** you'll have to convert the floating point values to fixed-point 64-bit representation. If the value is an integer, then it's easy, it's just `x << 32` (bit shift left 32 places). If the value has a fractional part it gets a bit more complicated, but I've been using this program to convert `floats` to their 64bit fixed-point representation:
```c
#include <stdint.h>
#include <stdlib.h>
#include <limits.h>
#include <stdbool.h>
#include <stdio.h>
#include <assert.h>
#include "FixedMath/Fixed64.h"
#include "FixedMath/FixedUtil.h"

int main(int argc, char** argv) {
  double n = 0.51266;
  
  if(argc >= 2) {
    n = atof(argv[1]);
  }
  
  FP_LONG v = FP64_FromFloat(n);
  printf("%lf -> %ldll\n", n, v);
}
```

You should be able to compile it in the driver directory `/LeetMouse/driver/`. But if not, I'll also attach a [compiled binary](https://github.com/user-attachments/files/17791663/double2fixed-point.gz). (I had to gzip it, github wouldn't let me upload it other way)

At the end, I don't really know what's the best solution. I could make a service that starts with the system boot and applies the config to the driver, but that's risky and a lot can go wrong in that process. Other approach would be to allow users to save and apply configs from some `.json / .xml` file, but that would require opening the GUI every time. If anyone has ideas, on how to tackle this, feel free to share them.

**Comment by dougg0k** [comment]
Dont worry about it. Like I said, just reporting it.

**Comment by AndyFilter** [comment]
*Sorry, for writing in a closed issue, again.* But I have found a little bit of time to add some of the changes (https://github.com/AndyFilter/YeetMouse/commit/df1e44b18522c483d8858b85dd5887798a7d2867) we talked about here earlier, so I wanted to let everyone who was interested, that the program now supports **Importing and Exporting** parameters. With this, it should be very easy to just set the parameters you like the most in the GUI, export them to a config.h file and rebuild the Driver to have the values **persistent between reboots**. Though the GUI is not necessary now, as you can just type **floating point values** in the **Config.h** file.

Also, the _Devices_ tab _should_ work. But I only added some error handling, so if the issue is more serious (some OS specific thing) you'll at best just see nothing there.

_Let me know if You have any issues with the new (or old) features, as they might be a bit unstable since I had little time to test them._

**Comment by dougg0k** [comment]
```
...
==> Creating package "leetmouse-driver-dkms"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
error: could not open file /var/lib/pacman/local/leetmouse-driver-dkms-0.9.0-1/desc: No such file or directory
  -> Adding install file...
  -> Generating .MTREE file...
...
```

```
nu ❯ sudo pacman -U pkg/build/leetmouse*.zst
loading packages...
warning: leetmouse-driver-dkms-0.9.0-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...
error: could not open file /var/lib/pacman/local/leetmouse-driver-dkms-0.9.0-1/desc: No such file or directory
warning: could not fully load metadata for package leetmouse-driver-dkms-0.9.0-1
error: failed to prepare transaction (invalid or corrupted package)
```

**Comment by AndyFilter** [comment]
Ok, I'm going to be honest here, Linux is not my strong side. The only distro I'm familiar with is Ubuntu, and it's not much, but I'll try to help.

I assume, you're running `Arch/Manjaro`. After looking at the install scripts for that distro, and the errors logs You sent (thanks for all the details btw. <3), it seems that the path /pkg/build/ doesn't exist:
```
error: could not open file pkg/build/leetmouse-driver-dkms-0.9.0-1-x86_64.pkg.tar.zst: No such file or directory
```
Now, the only reference I could find about this is here:
https://github.com/AndyFilter/YeetMouse/blob/df1e44b18522c483d8858b85dd5887798a7d2867/scripts/build_arch.sh#L23-L28

This is the /scripts/build_arch.sh file. And looking back again at the instructions. So try again, uninstalling all the instances of the `leetmouse` driver (as much as you can), and then running that build script like so:
```bash
./scripts/build_arch.sh
```
Which is pretty much just going to the beginning of the install instructions:
https://github.com/AndyFilter/YeetMouse?tab=readme-ov-file#archmanjaro

If that helped, I'm glad it's not some distro-specific problem!

Sorry if this wasn't helpful, like I said, my knowledge here is very limited.

**Comment by dougg0k** [comment]
I might have found why. Previously I was on gnome and the problem did not appear. Now I tried on KDE. It seems to be the automate complete with the wildcard. By using the full name of the tar.zst file, it worked.

**Comment by dougg0k** [comment]
There might be new bugs added though. It's like at least in the chart, the sensitivity does not go up as before.

https://github.com/user-attachments/assets/0895a03c-4618-41a4-b5b9-4121a9429871

**Comment by AndyFilter** [comment]
I'm glad you found the solution.

When it comes to the video. Yes, this is intended behavior. As far as I'm aware it was wrong all the time, and now it should be right. Thought I must admit, the current "sensitivity" seems small. I'll run some tests in the near future to test that.

Also, this is just a visual thing, nothing inside the driver changed, so don't worry.
