### ISSUE TITLE
Anisotropy X / Y support

### ISSUE THREAD

**Issue by dougg0k** [AndyFilter/YeetMouse#12]
Hi,

Any chance of adding anistropy x/y? 

It doesn't need to be complex, just the individual sensitivity for the X and Y.

**Comment by AndyFilter** [comment]
Yes, as I said in the comment here: https://github.com/AndyFilter/YeetMouse/issues/11#issuecomment-2474333113. Anisotropy is planned for the future. But I'm glad You asked for it, as I have a couple of questions regarding this topic.
1. What parameters would you want to have anisotropy on? Like sensitivity, acceleration, etc. It's not a big deal to have it on more parameters than just sensitivity (I think).
2. How would you want to have it implemented? Something like a checkbox next to every parameter that enables anisotropy for it? Or a separate tab that would only have parameters with anisotropy on?
3. How to make it so it doesn't affect users who don't want to use it?

These are the most difficult question I'll need to find answers to before starting the work on this feature. If anyone has any suggestions about these, feel free to share them, it will greatly speed up the implementation process.

**Comment by dougg0k** [comment]
Just separated sensitivity, like I mentioned. Checkbox to show both sensitivity input would work. 

It doesnt really matter on the UI, as it should be easy if you have the config.h file. In fact, if you consider 1 as 100%, by having it only on the config file, it should be enough for starting.

**Comment by owosoup** [comment]
I'm all for this. Having a small desk sucks for vertical movement, decoupling x and y sensitivities helps. A basic multiplier config entry is enough.

**Comment by AndyFilter** [comment]
Alright, it took me some time, because I like to finish other things before starting new ones.
But anisotropy should be working on the [feature branch](https://github.com/AndyFilter/YeetMouse/tree/feature/anisotropy). Check it out, and let me know if you would add / change anything.
Keep in mind, this is a feature branch, meaning it can contain bugs (it shouldn't, but it might).

**Comment by dougg0k** [comment]
So this is the sensitivity X now? https://github.com/AndyFilter/YeetMouse/commit/8f6d77c2ee7a3289848a1f0a70858f39d4bb9403#diff-ce91cd52953658f8dbaeb35bf1ae9d6b23e649f657c7a20921beab9fe8db65e1R56

**Comment by AndyFilter** [comment]
Yes, this is "Sensitivity X" when anisotropy is on. But it's also just "Sensitivity" when anisotropy is off. So I went with just naming the Y axis to "Sensitivity Y", and leaving the sensitivity as is, because most people don't use anisotropy I think.
So if you want to have sensitivity of 2 (on both axes), you only have to change "Sensitivity" instead of "Sensitivity X" and "Sensitivity Y" to the same value. So anisotropy is only on when the values of "Sensitivity" and "Sensitivity Y" are not equal.
This kind of goes back to the fact that all the parameters are *multi-purpose*, like for example the *Jump* mode uses *Exponent* parameter as a value named *Smoothness*. The parameters are not really meant to be changed manually.
![image](https://github.com/user-attachments/assets/a08d9ca3-c547-49cb-ab5d-137cb7e9aa10)
Let me know if this makes sense.

**Comment by dougg0k** [comment]
Why not be changed manually?

**Comment by AndyFilter** [comment]
Because there is GUI that's meant to do all these things for you. But you **can** change things manually if you want, you just have to know exactly what you're doing. You're simply going "off the rails" by changing them manually, because for example, there is nothing stopping you from setting 2000 LUT values, which the driver might not like... and weird behavior might happen.
Don't get me wrong, there's nothing really wrong with it, you just have to know what you're doing.
That's why I'm not planning my program around these parameters being visible or directly available to the average user. It's a *backend*.

**Comment by dougg0k** [comment]
GUI does not persist changes, so, shouldnt be only through it.

Obviously. You get the values from the setting you want and put them to manual.

---

To be honest, leetmouse or this tool are completely different from rawaccel in mouse feel and behavior even with similar setting. I was not able to find something I liked, only some improvements. Not sure if the algorithms are complety different or what.

**Comment by AndyFilter** [comment]
I don't see how GUI persist changes different than changing the parameters manually. I think you're talking about changing the *config.h* and reinstalling the driver, but that too is arguably made easier by the GUI through the `Export` function.

Yes, you're correct, the algorithms are completely different in RawAccel, especially the motivity (one of 2 that's really changed), because they changed it quite recently and I think it's even named *synchronous* now.
(from the [RawAccel Docs](https://github.com/RawAccelOfficial/rawaccel/blob/master/doc/Guide.md#synchronous))
![image](https://github.com/user-attachments/assets/383c829a-fee2-4093-a58c-938f4bcd96a0)
And I simply use a basic sigmoid function to do what RawAccel had "back in the day". And really this sigmoid function can be made from *Jump* if you set the parameters right, so you're correct, the *Motivity* mode is not really fully featured like it is in RawAccel. I'm gonna be honest, the reason why `Jump` has *Gain* is simply because I use it, and it was the first thing I implemented to this program, but this doesn't mean that I don't add things I don't use, for example rotation, angle snapping, anisotropy and more.
Also keep in mind that if the feeling is "off" in YeetMouse, that might be caused by your OS that's adding sensitivity on top. I encountered this behavior in Ubuntu 20.04, where I had to lower the sensitivity to -0.66 I believe, to get the exact RawAccel "feeling". I use an Arduino Pro Micro to simulate a mouse movement at a given speed and compare them to results I got on Windows with RawAccel (with the same settings), so I can be pretty certain that it's correct. All that is obviously done through a python script, and the results (with well configured OS) are as follows:
![image](https://github.com/user-attachments/assets/66907cf1-059e-4cc4-947e-64a2ad940cd4)
*(keep in mind that the difference between the exact function and RawAccel / YeetMouse is caused by the inaccuracy in high speed movements, as the mouse can only move in integer values. What I want to check with this is the difference between YeetMouse and RawAccel, which is pretty much non-existent)*
In the end, feeling is just a feeling. It might be caused by different things, that's why I have developed a tool like this to measure exactly the difference between the curves. On Linux when your PC freezes for a second, so does the mouse, even with some micro stutters, these might cause the *feeling* of different curves, even tho they are the same, and there is nothing I can do to fix micro stutters on Linux, nor the effects of them. Unless the HID driver that's being worked on by the community somehow gets rid of them (Let's pray that it does).

In the end you can always just use LUT to get the exact "feeling" you want. While I work on features such as *Synchronous*, or *Gain* for *Motivity*. 

About the scale of the speed on plots. I think I've mentioned it somewhere earlier, but there **was** an issue, that I've fixed. The issue was that when I was reworking the mouse speed capture code I felt like "no way the mouse is this slow", so I just multiplied the values by 10. As you can see, this was not very "correct", so I [fixed it](https://github.com/AndyFilter/YeetMouse/commit/df1e44b18522c483d8858b85dd5887798a7d2867#diff-eb5b173cad4e08626b0d7498a036ece19ab3b71b87935b423381ba457120e929R313) some time after when I fully validated and checked the code. So now the speed you get on graphs is right, I've even tested it with my python script, and cross checked it with RawAccel (obviously), and right now I'm pretty sure it is correct. As always, I'd like to be proven wrong. Also, if you change your DPI it's going to move further, as it increases the amount of *counts* mouse registers, which is the exact thing the graph presents.

**Comment by dougg0k** [comment]
Unless there are some unknown configuration or something else that I missed, the OS should not be doing anything more, as it is optimized in every front, kernel and through configurations.

It just doesnt reach the same feeling, but sure, in windows previously I had a even more tweaked version that could have somewhat helped, but still It didnt seemed to be due to it.

**Comment by AndyFilter** [comment]
Not much I can help on the OS side, as I never dug into inner workings of Linux. If you know it's not the OS's fault, I believe you, as you seem to be more knowledgeable than me on this topic.

The `Pre-Scale` parameter is there to account for different DPIs. Precisely it allows you to preserve the same curve while having a different DPI. Meaning some mouse movement on 400 DPI would be in the same place on the curve with 3200 DPI if the `Pre-Scale` is set correctly (2 for 400DPI and 0.25 for 3200DPI). This does **not** affect the sensitivity, your cursor will still be moving 8 times faster with 3200DPI.

Yes, you will not be able to get the same *feeling* with Motivity as in RawAccel, currently you'd have to use LUT. This is because my calculations looks like this:
![image](https://github.com/user-attachments/assets/ae027ae2-b97c-485f-9a9c-ab5c9cf3eda7)
And RawAccel's like so:
![Screenshot from 2024-12-31 17-15-44](https://github.com/user-attachments/assets/3a9cd599-690d-454d-bfb6-57e0edd13fd2)
Obviously, the graphs look different, but both are just sigmoids, maybe the naming is misleading as it *suggests* that it's the same as in RawAccel. I can change the name from "Motivity" to "Sigmoid" if that helps, but then people would just ask "Where is Motivity?". I'll try to do some research and find some more fitting sigmoid function that will better represent the one RawAccel.

I don't know if you've tried other modes, like `Power`, or `Jump`, all modes beside `Motivity` are pretty much 1:1 like in RawAccel.

LUT stands for *"Look Up Table"*, the last mode in the GUI.

**Comment by dougg0k** [comment]
Cool.

Ok.

I've tested anisotropy and it works. That finishes the issue, thanks for answering all the questions.
